//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDietetyk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diets
    {
        public int Id { get; set; }
        public string IdUser { get; set; }
        public int CaloriesPerDay { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
