//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDietetyk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metrics
    {
        public int Id { get; set; }
        public string IdUser { get; set; }
        public int Height { get; set; }
        public decimal Weight { get; set; }
        public Nullable<int> Chest { get; set; }
        public Nullable<int> Waist { get; set; }
        public Nullable<int> Thigh { get; set; }
        public Nullable<int> Arm { get; set; }
        public bool IsTarget { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
